### ISSUE TITLE
Java Project Setup too hard.

### ISSUE THREAD

**Issue by IRus** [CoatiSoftware/SourcetrailBugTracker#178]
I just trying to setup project link-rest https://github.com/nhl/link-rest/tree/master/link-rest
I manually selected link-rest/link-rest/src/main/java as project path. And doesn't select any libraries as classpath. I expected that my dependencies doesn't shown in Coati, but i expect that current JDK library selected automatically.

Also link-rest uses maven for dependency management, other projects used gradle. I think it's must have to read configuration for classpath from build.gradle(gradle) or pom.xml(maven).

**Comment by mlangkabel** [comment]
Hi @IRus, thanks for reaching out to us. What do you mean by "i expect that current JDK library selected automatically"? 
Do you mean that Coati should automatically find your Java Runtime? 
Or do you mean that symbols that are defined in the JDK libraries are displayed as "undefined"?

**Comment by IRus** [comment]
Hi, I mean symbols that are defined in JDK displayed as undefined.

On Sep 5, 2016 16:14, "Malte Langkabel" <notifications@github.com> wrote:

Hi @IRus <https://github.com/IRus>, thanks for reaching out to us. What do
you mean by "i expect that current JDK library selected automatically"?
Do you mean that Coati should automatically find your Java Runtime?
Or do you mean that symbols that are defined in the JDK libraries are
displayed as "undefined"?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CoatiSoftware/CoatiBugTracker/issues/178#issuecomment-244744189>,
or mute the thread

**Comment by mlangkabel** [comment]
They are displayed as undefined because Coati did not index the definition of those symbols (because they are not contained inside your project's source code). But maybe this is a really poor choise of words on our terms. 
We should rename "undefined" to "non-indexed" in these cases. What do you think about that?

**Comment by IRus** [comment]
Can we just attach sources of OpenJDK (since they available)? And how to deal with other project dependencies?

**Comment by mlangkabel** [comment]
There is a difference between "undefined" (or "non-indexed") symbols and symbols that the indexer simply cannot find. 
Think of your Coati project as two layers. 
* The first layer (or the core) is the source code you put into Coati. Coati indexes that code and whenever you click a symbol (a method for example) it shows you the definition of the method plus all locations where it is called.
* The second layer is more like the surrounding of that core. That's what you specify in the dependencies. Symbols in the dependencies are needed to compile and also to index the core. When you click a symbol here (e.g. String) it shows you all the locations where the symbol is used, but it won't show the symbols definition (because the definition is not indexed). 
So when something is displayed as "undefined" or "non-indexed" that's not a bad thing.

Here's what to do: Coati knows everything from the JRE (like String) by itself. You don't have to worry about that. For other dependencies just put the jars into the dependencies listbox. 
If your project (A) depends on the jars (B) and (C) but the internals of jar (B) contains some interesting types you want to know more about, just remove (B) from the dependencies and add the root folder of (B)'s source code to your project directories, right next to the source folder(s) of (A).

**Comment by mlangkabel** [comment]
To summarize this discussion I opened the issue #199 for Maven / Gradle support .

**Comment by IRus** [comment]
Sorry, miss your comment.
> Here's what to do: Coati knows everything from the JRE (like String) by itself. You don't have to worry about that.
Yep, that what i mean. 

> If your project (A) depends on the jars (B) and (C) but the internals of jar (B) contains some interesting types you want to know more about, just remove (B) from the dependencies and add the root folder of (B)'s source code to your project directories, right next to the source folder(s) of (A).
So you doesn't plan support dependencies and transitive dependencies index without extra actions from users side? Often source and javadoc published along with artifacts(https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html). I suggest add ability for user to download and attach sources in one-click.

**Comment by mlangkabel** [comment]
Thanks for pointing that out! Adding a one-click solution for adding dependency source code would be awesome. The problem here is that when adding a depedency to be indexed alongside the main project Coati would be required to know the dependencies of the dependency as well. We'll need to look into this a little more, but I think adding basic support to import a maven project should be the first step!

**Comment by IRus** [comment]
It's shouldn't be problem if we import jars from maven/gradle build system.

For example part of pom.xml:
```
<dependency>
    <groupId>com.nhl.link.rest</groupId>
    <artifactId>link-rest</artifactId>
    <version>2.1</version>
</dependency>
```

All dependencies of `link-rest` artifact can be found alongside of jar:
jar: http://central.maven.org/maven2/com/nhl/link/rest/link-rest/2.1/link-rest-2.1.jar
dependencies: http://central.maven.org/maven2/com/nhl/link/rest/link-rest/2.1/link-rest-2.1.pom
sources: http://central.maven.org/maven2/com/nhl/link/rest/link-rest/2.1/link-rest-2.1-sources.jar

**Comment by mlangkabel** [comment]
Great! I'll look into it. But it will probably take some time until all of this is implemented ;)

**Comment by IRus** [comment]
No problem! Just pointing you for common practices in java world :)
Also you can take a look at IDE's plugins, for example:
Eclipse's Maven Integration: https://github.com/eclipse/m2e-core
Intellij's Maven: https://github.com/JetBrains/intellij-community/tree/master/plugins/maven
Intellij's Gradle: https://github.com/JetBrains/intellij-community/tree/master/plugins/gradle

**Comment by egraether** [comment]
Most or all of the mentioned issues have been addressed since this was opened. Closing.
