### ISSUE TITLE
clang PCH problems

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#311]
I am using a clang based project on Linux that uses PCH and I see a variety of errors:

```
Error while processing [.cpp] 
error: exception handling was disabled in PCH file but is currently enabled
error: PCH file was compiled for the target 'x86_64-pc-linux-gnu' but the current translation unit is being compiled for target 'x86_64-unknown-linux-gnu'
```

And this also:

```
error: PCH file uses an older PCH format that is no longer supported
```

(this one happens on an older version of the source that requires clang 3.5)

**Comment by pron** [comment]
See similar issue and solution in another tool: https://github.com/facebook/infer/issues/96

**Comment by mlangkabel** [comment]
Thank you for the pointer!

**Comment by pron** [comment]
I'm afraid this has now become a blocking bug for me, and I can no longer use SourceTrail (not conveniently, at least).

**Comment by egraether** [comment]
@pron Thanks, we will look into it!

How did you work around this issue so far? And why did it become blocking now?

**Comment by pron** [comment]
I've used another configuration of the build without precompiled headers, and it's becoming inconvenient, as now it exists only to satisfy Sourcetrail. I can probably hang on to it for a while more.

**Comment by mlangkabel** [comment]
Quick update: We are currently looking into making PCH support available for the "empty c/c++" Source Groups.

Getting PCH support ready for Source Groups that are based on a compilation database will be tricky, because the flags used for generating the PCH file need to match the flags used for the actual translation units (as @TTimo pointed out in the original submission) and in theory every translation unit of a compilation database can have a different set of arguments.

**Comment by mlangkabel** [comment]
Implemented PCH support for Empty C Source Group and Empty C++ Source Group with Sourcetrail 2019.3.6. Enabling PCH support for Source Groups that depend on a Compilation Database will be a different story, but sill may be part of the next release.

**Comment by egraether** [comment]
Added PCH support to CDB Source Groups with 2019.3.18
