### ISSUE TITLE
Error when indexing Borland-style C++ code

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#402]
This is correct in C++ compilers like Borland:
```
for(int i = 0; i < 8; i++){ }

for(i = 0; i < 4; i++){ } <- Error: use of undeclared identifier "i"
```
Using `-fborland-extensions` does not solve it.

**Comment by mlangkabel** [comment]
There should be a flag to enable the behavior (which is actually not part of the standard). This flag is called `-fno-for-scope`. Setting this flag causes variables that are declared inside the for scope to be also visible in the parent scope of the for loop. However, when trying to use this flag I get the following error:
```
error: the clang compiler does not support '-fno-for-scope'
```

So I decided to investigate and looked at the Clang codebase:
![clang_fno_for_scope](https://user-images.githubusercontent.com/16242920/27587151-82039aee-5b43-11e7-82e0-9594090bb942.png)

It seems like the flag is only referred to once. And this reference is only there in order to tell the user that this flag is not supported. So we do not have any means to fix this issue.
