### ISSUE TITLE
Does not handle msvc-style flags

### ISSUE THREAD

**Issue by Ozaq** [CoatiSoftware/SourcetrailBugTracker#444]
I use cmake & ninja inside an visual studio 2017.3 command line environment with a c++14 codebase.

During indexation Sourcetrail complains that:
- std::make_shared is unknown
- thread header is unnown
etc...

Given the type of errors it looks like the c++ standard setting is not properly passed on to clang.
NOTE: In my compile_database.json I do see the /std:c++14=

**Comment by egraether** [comment]
It works when the standard is present in the compile_database.json.
Does your flag literally look like this `/std:c++14=`?
Because it should look like this: `-std=c++14`

Other than that my guess is that your **Global Include Paths** are not correctly detected. Please open the preferences and check if the paths at **Global Include Paths** really point to the location of your std library files.

**Comment by egraether** [comment]
@Ozaq Could you resolve your issue?

**Comment by mlangkabel** [comment]
It looks like the clang compilation database contains Visual Studio style flags that Clang doesn't understand.

To generate a clang compilation database with Clang style flags you can use cmake in order to create a Visual Studio project and use the [Sourcetrail Extension for Visual Studio](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1208751.SourcetrailExtension) to export a compilation database from this Visual Studio project.
