### ISSUE TITLE
Project setup for Archi via Maven results in 0 Indexed files

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#449]
https://github.com/archimatetool/archi

**Comment by mlangkabel** [comment]
It looks like this is a timeout issue. Maven just takes longer than we expected to generate the information Sourcetrail needs.

**Comment by mlangkabel** [comment]
fixed with Sourcetrail version 2017.3.29

**Comment by Phillipus** [comment]
Hi, tried again with version 2017.3.48. Am getting the following error:

![image 1](https://user-images.githubusercontent.com/600504/30184962-977d58da-9417-11e7-9cb5-2f026f5abcbc.png)

I see that in the dependencies folder there is a file "com.archimatetool.jdom-4.0.3.qualifier-jdom-2.0.5.jar.jar"

**Comment by mlangkabel** [comment]
I think I ran into the same issue while testing on the Archi project. I suspected that the pom references a snapshot version of that missing jar which wouldn't be found on maven central or anywhere else. So my thought was that this missing jar would be built by the project itself and after executing `mvn install` for the Archi project the issue was gone. Can you please give that a try?

**Comment by Phillipus** [comment]
Hi, I don't quite understand how to go about this. Do you mean add the source jar to the index?

**Comment by mlangkabel** [comment]
No problem, I had to run `mvn install` from within the root folder of the Archi project. That caused maven to build and install the Archi related jars in my local Maven repository and Sourcetrail was able to fetch the correct jars on its own.
