### ISSUE TITLE
Add option to specify exported graph image quality

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/SourcetrailBugTracker#473]

**Comment by xueyayang** [comment]
Yes I need this feature too. I think it should works like the Export menu in other software like Xmind or others. Users can choose the format of image, meanwhile can  crop the image to the graph node.

Why i need this function? Because the  graph generated in Sourcetrail is so nice to imbed in a documents. It’s beautiful and power-in-explaining.

Again, you are doing great job. A more rich context menu maybe a good point for charging  :-)

**Comment by GitGoogol** [comment]
Yes, that would be great. I also use it for documentation stuff and therefore it would be nice to have such an option

**Comment by egraether** [comment]
Generally improved image quality with 2018.1.

**Comment by egraether** [comment]
No more requests regarding this since image quality was improved. Also SVG export was added. Closing.
