### ISSUE TITLE
Why are my .tcc files not indexed by Sourcetrail?

### ISSUE THREAD

**Issue by kernhanda** [CoatiSoftware/SourcetrailBugTracker#482]
I have a codebase that uses *.tcc files to provide template class method definitions outside of the class definition. SourceTrail doesn't seem to be indexing these files.

**Comment by egraether** [comment]
They are not indexed if:
* their containing directory is not listed within your project's "Indexed Paths"
* None of your source files use them within their include tree, so they are never encountered by our indexer.

**Comment by mlangkabel** [comment]
What @egraether was saying is that this is totally normal behavior for every compiler. A compiler starts one translation unit for each source file (.cpp) it encounters. Using this translation unit it tries to translate the source file and all the header #include hierarchy (including .tcc files which are #included by template headers) to machine code.

What the compiler doesn't do is starting a translation unit for a .tcc file it encounters. If it did it would quickly run into an error because the .tcc file only contains the definition of methods of a template class but it doesn't #include the header file that contains the template class' actual definition.

Sourcetrail does the same thing. When indexing your source code it utilizes a compiler (frontend) that only starts translation units for each of your source files.

**Comment by kernhanda** [comment]
The problem was occurring for me because the tcc files are in a separate directory from the header files. So, while the tcc files were being included in translation units (because they're included in header files which are included in cpp files), they weren't being indexed properly.

Adding the tcc specific folders fixed the problem.
