### ISSUE TITLE
Low contrast of text cursor in dark theme

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#487]

**Comment by ggilles** [comment]
Please note that the problem comes both from low-contrast and low-width of the cursor. See attached file for a visualization of the problem. The cursor is very thin. If you can't find it, it is a the beginning of the input.

![cursor](https://user-images.githubusercontent.com/1478233/32161806-2767f87a-bd57-11e7-971a-8f302bbc6b3f.png)

**Comment by egraether** [comment]
Thanks! I had a look into the Qt documentation and it seems that there is no easy fix for this. I can't just change the cursor's width or color.

**Comment by ggilles** [comment]
I found this:
https://forum.qt.io/topic/1137/change-qlineedit-text-cursor-shape

Which seems to be a possible solution, granted it's not perfect and does not integrate with other Qt styling APIs, but if it work that would be great.

**Comment by egraether** [comment]
Thanks for the hint. It's not possible to change the cursor color with this approach though. And there is no other way to set the cursor color. I found out that a QLineEdit will uses the invert of the background color for the cursor color. So the only possible solution I found so far is changing the color scheme.

**Comment by egraether** [comment]
Fixed with 2017.4.22
Using a different style for the search field in the dark color schemes now:
<img width="148" alt="screen shot 2017-10-30 at 23 00 55" src="https://user-images.githubusercontent.com/201867/32229872-1bf7a868-be52-11e7-88eb-6be6925fda83.png">
