### ISSUE TITLE
Make it possible to add custom language support using plugins

### ISSUE THREAD

**Issue by joukevandermaas** [CoatiSoftware/SourcetrailBugTracker#499]
There are [many feature requests](https://github.com/CoatiSoftware/SourcetrailBugTracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22language+request%22) for new language support. It's unlikely that your team will be able to add support for all of them. But, by allowing anyone to create a "language support plugin", the language communities can add this support themselves.

The plugins must be able to provide all symbols, their location in the source files and their relationships. Sourcetrail will then use this information to navigate and explore the code as it does now.

**Comment by mlangkabel** [comment]
This sounds like a really good idea! For this to be feasible we need 
* to generalize our data format for storing the indexed symbols a little bit more so that it doesn't just work for C, C++ and Java
* to reshape the internals of the project setup, so that plugins could define what kind of things the user needs to enter there
* to pass that plugin-project specific data to the plugin's indexer
* to allow the plugins to expand Sourcetrail's application settings and query data from those settings

This sounds like it will be some amount of work for our team but it also sounds quite doable!

**Comment by manokara** [comment]
This would indeed be great! Please keep us posted whenever there's some development on this matter.

**Comment by egraether** [comment]
+1 via email

**Comment by egraether** [comment]
We decided to realize this request in a simpler way with our recently released [SourcetrailDB](https://github.com/CoatiSoftware/SourcetrailDB) library. It allows for creating and exporting Sourcetrail compatible project files (`.srctrlprj` and `.srctrldb`). This means that anyone can write custom language support using this library. The great thing about it is that new indexers can be written in any language using language bindings.

We are already working on [Python support](https://github.com/CoatiSoftware/SourcetrailPythonIndexer) using this new approach. Read about it in our [blogpost for Release 2019.1](https://www.sourcetrail.com/blog/release_2019_1/)
