### ISSUE TITLE
Hide items via context menu

### ISSUE THREAD

**Issue by GitGoogol** [CoatiSoftware/SourcetrailBugTracker#539]
It would be great when I can hide items that I don't want to export. So the exported picture doesn't show any unimportant stuff.

**Comment by mlangkabel** [comment]
Hi @GitGoogol, thanks for all your suggestions!

Which version of Sourcetrail are you currently using? I'm asking because this feature has already been implemented. It will be part of our next release and can already be used with that release's beta (2018.1.0). 

You can find the download here: https://www.sourcetrail.com/downloads#beta
