### ISSUE TITLE
"Show caller graph" option does not work for a function called by thread_create()

### ISSUE THREAD

**Issue by jetm** [CoatiSoftware/SourcetrailBugTracker#583]
I have a C function main(). Function main() creates threadA and it calls func_calledbythreadA().

I want to know who is the caller of func_calledbythreadA(). If "Show caller graph" is used, it should show main() as the caller, but it doesn't. You can test it with the following code:

```c
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void *func_calledbythreadA(void *vargp)
{
    sleep(1);
    printf("Printing from threadA \n");
    return NULL;
}

int main()
{
    pthread_t threadA;
    printf("Before ThreadA\n");
    pthread_create(&threadA, NULL, func_calledbythreadA, NULL);
    pthread_join(threadA, NULL);
    printf("After ThreadA\n");
    exit(0);
}
````

**Comment by mlangkabel** [comment]
Hi @jetm, in the code you provided `main()` doesn't call `func_calledbythreadA`. Instead `func_calledbythreadA` is passed to `pthread_create()` as an argument. So `func_calledbythreadA` may be called somewhere inside the 'pthread_create' function, but this actually is dynamic information, which cannot be derived directly from looking at the code of the `pthread_create` function. 

As Sourcetrail only uses static code analysis it doesn't know about any potential call of the arguments used for parameters that are function pointers.

**Comment by jetm** [comment]
Hi @mlangkabel,
Yes, it's called by pthread_create() but this function is in main(), so at least it should show pthread_create() and extended until main(). It doesn't show either. 
Clion IDE does it, as well as MS Visual Studio. I think this issue is not solved and it should be open.

**Comment by mlangkabel** [comment]
Hm, when I run Sourcetrail on that code I see this:
![pthread](https://user-images.githubusercontent.com/16242920/40147358-a5fd0320-5969-11e8-841b-daa1c573866d.png)

Can you show an example of what you mean? How does Clion or VS show that?

**Comment by mlangkabel** [comment]
I see. In Sourcetrail we show a "useage" edge that goes from `main` to `func_calledbythreadA`, because even though `main` references `func_calledbythreadA` our static analysis cannot be sure that it is actually called. `pthread_create` could also just require you to pass a function pointer as an argument but completely ignore it internally. Or it could call the function pointer that you passed only in a certain `if` branch.

So that's all dynamic information which depends on what actually happens at runtime. And since Sourcetrail is a static code analysis tool it doesn't show this information.
