### ISSUE TITLE
include_next make fatal_error

### ISSUE THREAD

**Issue by Milerius** [CoatiSoftware/SourcetrailBugTracker#608]
> Fixed detected global header search paths lost correct order and caused problems with #include_next directives

I'm not sure 

<img width="1671" alt="capture d ecran 2018-08-15 a 08 43 52" src="https://user-images.githubusercontent.com/21139416/44135003-7740d35a-a067-11e8-8b41-39084265a714.png">
<img width="1675" alt="capture d ecran 2018-08-15 a 08 44 11" src="https://user-images.githubusercontent.com/21139416/44135004-77593576-a067-11e8-8104-8d276e29f8bc.png">

i have stddef.h in my directory and he complains that's is not present

<img width="718" alt="capture d ecran 2018-08-15 a 08 46 57" src="https://user-images.githubusercontent.com/21139416/44135082-cf84b072-a067-11e8-993b-5558b3f38554.png">

**Comment by egraether** [comment]
The problem is that for `#include_next <stddef.h>` the file needs to be found with another header search path, not in the same directory.

We ship the correct `stddef.h` within our build, it's located within the first path `/Applications/Sourcetrail.app/Contents/Resources/data/cxx/include`.

It looks to me like you are using multiple c++ toolchains simultaneously, which causes inconsistencies. The error occurs in the file `usr/local/Cellar/llvm/6.0.0/include/c++/v1`. Did you add that path to the Global Header Search Paths? Why? Or was it automatically added? Try removing it.

**Comment by Milerius** [comment]
> The problem is that for #include_next <stddef.h> the file needs to be found with another header search path, not in the same directory.

Sorry but my default toolchain is clang-6.0 and do not use the XCode one, Sourcetrail added it by default.

In the llvm clang-6.0 include directory stddef.h is in the same directory.

Yeah i added the path of my llvm toolchain since i didnt't use the standard one (which doesn't support c++17)

**Comment by egraether** [comment]
I see, then remove all Xcode paths and see if that helps. What about the `usr/local/opt/...` paths. Are you using those? Remove everything not part of your toolchain.

Maybe you need to move `/Applications/Sourcetrail.app/Contents/Resources/data/cxx/include` to the end of the list.

It will need to some trial and error unfortunately.

**Comment by egraether** [comment]
@Milerius Could you resolve your errors?

**Comment by Milerius** [comment]
@egraether Hey i'm at holliday until 31 august, i will reopen the issue if i have a problem !
