### ISSUE TITLE
Indexing non-selected files (from CDB).

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#634]
I am using version 2018.4.8 - 64 bit on Centos 7.

It seems that with this new version, Sourcetrail is indexing files (from the CDB) which are NOT selected inside the Select from Compilation Database (and those files do not appear in the resulting Header Files and Directories to Index).

I had some troubles with Sourcetrail being stuck, and I think it's because of the too many files it is now trying to index. Anyway I had to kill all the left-over processes (/opt/sourcetrail/Sourcetrail and/or /opt/sourcetrail/sourcetrail_indexer ). I did not reboot my PC yet. Not sure if there is additional cleanup to do.

Looking at the log, and at the info or reported errors, I see those files being indexed. For example:

15:32:23 | 140080331053120 | main.cpp:83 main() | INFO: appPath: /opt/sourcetrail/
15:32:23 | 140080331053120 | main.cpp:84 main() | INFO: userDataPath: /home/corp.roku/pwillard/.config/sourcetrail/
15:32:23 | 140080331053120 | InterprocessIndexer.cpp:27 work() | INFO: 1 starting up indexer
15:32:23 | 140544576354368 | CxxParser.cpp:202 runTool() | INFO: Clang Invocation errors: error: unknown argument: '-fabi-version=8'
15:32:23 | 140080331053120 | InterprocessIndexer.cpp:60 work() | INFO: 1 fetched indexer command for "/home2/perforce2/dev/3rdParty/PlayReady/Device_PK_2.0.0/Source/blackbox/blackbox.c"
15:32:23 | 140080331053120 | InterprocessIndexer.cpp:61 work() | INFO: 1 indexer commands left: 19
15:32:23 | 140080331053120 | InterprocessIndexer.cpp:76 work() | INFO: 1 updating indexer status with currently indexed filepath
15:32:23 | 140080331053120 | InterprocessIndexer.cpp:79 work() | INFO: 1 starting to index current file
15:32:23 | 140252749072448 | LogManager.cpp:41 setLoggingEnabled() | INFO: Enabled logging for Sourcetrail 64 bit, version 0.0.0

Here "/home2/perforce2/dev/3rdParty/PlayReady' is NOT selected in my project.
I see those files being indexed, I clicked STOP and it's stuck... Don't what I am doing wrong. Can you verify it is working or not?

thanks

**Comment by pwillard2** [comment]
I rebooted my PC, and tried again. 
And same thing, it is indexing files which are not selected (eg, /home2/perforce2/dev/3rdParty/bcm-2835/...) and then I tried to stop indexing, and it got stuck in 'Waiting indexer threads to finish'.
[log_2018-11-15_18-21-05.txt.gz](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/2587780/log_2018-11-15_18-21-05.txt.gz)

**Comment by egraether** [comment]
Sourcetrail will index all source files defined in the compilation database. **Header Files and Directories to Index** is used for defining which included header files should be indexed. If you want to exclude certain source files listed in the compilation database from indexing, you have to add those paths to **Excluded Files and Directories**

We looked at your log file. Your problem is that the database insertion thread is too slow. The indexer processes are way faster and indexed data is piling up, until the indexers stop and wait. Even if you interrupt indexing then, the indexers will keep waiting until they are able to push the data they already have to the main process. That's why you still see them as running processes. We will change this behavior, so that indexer just throw away the data when indexing is interrupted.

But that doesn't solve your problem. We hoped that our database speed improvements in the new release would avoid this problem, apparently they don't.

Some questions:
How much of your RAM is used during indexing?
What type of hard-drive do you have?
Is there a .srctrldb file stored after indexing, even if interrupted?
How large is the .srctrldb file?
Can you browse the indexed data?

At the moment you best option is to reduce the number of parallel indexers to e.g. 4.
Nonetheless, indexing should overall be faster than in the last version. Is this the case?

**Comment by pwillard2** [comment]
thanks for the information. I misunderstood that.


I am using a regular 500 GB SATA drive (7200 rpm I think).


After I killed the processes last night, I have the following files left:

-rw-r--r--   1 pwillard domain users       9859 Nov 15 18:23 giga-min2.srctrlprj
-rw-r--r--   1 pwillard domain users      17408 Nov 15 18:23 giga-min2.srctrldb
-rw-r--r--   1 pwillard domain users       9216 Nov 15 18:23 giga-min2.srctrlbm
-rw-r--r--   1 pwillard domain users   35293752 Nov 15 18:29 giga-min2.srctrldb_tmp-journal
-rw-r--r--   1 pwillard domain users   50169856 Nov 15 18:29 giga-min2.srctrldb_tmp


Indexing is faster and using less RAM.


I am going to try again with less indexer threads and less directories.

regards

Pierre


________________________________

**Comment by egraether** [comment]
Reduced the long wait times and stuck indexer processes when interrupting indexing with 2018.4.13

The SATA drive is most likely the reason why database insertion cannot keep up with the indexers.
