### ISSUE TITLE
C language feature request

### ISSUE THREAD

**Issue by PhilG57** [CoatiSoftware/SourcetrailBugTracker#678]
Sourcetrail Version 2019.1.11 64bit database version 23 --

Sourcetrail considers C language "memset" as a non-indexed function. Likewise, Sourcetrail flags "BOOL" and "DWORD" both as non-indexed symbols.

It would be nice to have a 'user preferences' file to instruct Sourcetrail on handling specific language data types.  For example, I would tell Sourcetrail to not consider memset as a function.  And that BOOL and DWORD are regular data types the same as int, char, etc.

Many thanks.

**Comment by mlangkabel** [comment]
Sourcetrail only counts very specific symbols to the group of "built-in" symbols. Usually, if your code uses these symbols, it doesn't require any includes. Every symbol that requires your code to include some definition code before you can use that symbol is therefore non-built-in.

For example if I try to use DWORD without specifying the proper include, Sourcetrail will tell me 
```
unknown type name ''DWORD''
```
So that's why Sourcetrail flags those things `symbol`s.

Moreover, it flags these symbols `non-indexed`, because they are simply not defined within the indexed part of the source code. 

So that's just a short explenation of the current state. Now let's get back to your request. What would you `DWORD`, `BOOL` and `memset` to be?

**Comment by PhilG57** [comment]
Hmmm.  I use the most excellent editor/compiler/debugger called Pelles C  (https://forum.pellesc.de/) which has always accepted DWORD and BOOL as double-word and Boolean (TRUE or FALSE) data types respectively.  I assumed they were baked into the C language definition.  Now having checked further, I believe DWORD and BOOL to be ‘extensions’ or ‘courtesies’ extended by Pelles to the programming community and probably not part of the basic language.  I’ve not contacted author Pelles for confirmation.  My request to Sourcetrail would be to consider these as data types and not to flag them at all.  Once again, if this capability were to be enabled/extended via a user “.ini” type file, that would be great.

 

As for memset, checking the Pelles documentation, I see it is an “intrinsic” function which generate in-line code.  I guess that would make it a macro definition…   And the easiest solution is to leave it flagged as is.  I know trying to be all things to all people is an honorable, but hopeless, task. 

 

Many thanks again for your responses and your program.  Once again, keep the pedal to the metal when supporting the C language.

 

---------------

.phil groben.

**Comment by mlangkabel** [comment]
Hm, so if Sourcetral can process DWORD and BOOL, they need to be defined in some source file. Maybe you can try to find out which source file that is and add that file to the list of source files you index. That would prevent DWORD and BOOL from being "non-indexed" symbols.

**Comment by PhilG57** [comment]
Thanks for the suggestion.  I think BOOL and DWORD are baked into the Pelles C compiler; in any case, I have them sprinkled all through my programs.

My solution was to add to my header files a couple of lines with --
#ifdef SOURCETRAIL
#define BOOL int
#define DWORD long
#endif	/* SOURCETRAIL */

and then add a -DSOURCETRAIL to the compiler flags section of the Sourcetrail project specifications which eliminates the errors.  That way, SOURCETRAIL and CLANG seems happy and I don't have to change a bunch of my files.

As far as I am concerned, you can close this support ticket.  Many thanks.
