### ISSUE TITLE
Java indexing sometimes missing progress dialog and using CPU in the background

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#694]
CPU usage of ~20% for hours (maybe due to running JVM)
reported via e-mail

**Comment by mrkdev** [comment]
Some additional Input:
How do you launch the indexer? I do not see any JVM process on my Windows 10 Machine. However, when starting Sourcetrail directly (the exe), I get a warning from Windows Defender. Thus I start it from a command line (cmd or cmder). Could it be the case, that Sourcetrail is not able to start the indexer due to Windows Defender restrictions? If this is the case, the 20% CPU load could result from Sourcetrail trying to execute an indexer process for each source fail but failing because of that restriction. Just guessing!

**Comment by mrkdev** [comment]
Just tried to reproduce the behaviour on my linux machine. No issues there. All works ok. So I assume, it is a Windows related issue...

**Comment by mrkdev** [comment]
And some last comment: I enabled detailed logging (also for indexing). The last message which I see there is the reindex all event. Nothing after that neither on the console nor in the logfile. Is there any additional log or other information that I can gather and send to you?

**Comment by egraether** [comment]
Sorry for the delay, we were busy with our new release.

I think your assumption is right, maybe Windows Defender is blocking the execution of your JVM. The JVM is only started once right before indexing, not for every source file. I guess Sourcetrail gets stuck when trying to execute the JVM.

We will look into it. Also let us know if you can figure out something.

**Comment by mrkdev** [comment]
I suppose that signing the SourceTrail executable could raise the trust level granted by Windows Defender and thus eliminate the problem.

However, as a workaround for concerned users: could you enable manual start of the JVM? As an example SourceTrail could provide a menu action 'Copy Indexer Run Command' that inserts the complete run command into the clipboard. That would allow the user to run the indexer directly from a windows shell.

**Comment by mlangkabel** [comment]
I'm afraid, running the Java indexer manually won't be possible, because it has some callbacks into our C++ code base for recording the extracted information to the main database.

**Comment by mrkdev** [comment]
Hi there, I come back to this issue with some new findings:

- The issue is related to setting the JVM Maximum Memory in Sourcetrail Settings
- I have 32GB of RAM; when setting any value other -1, Indexing never starts and one can see the issue with the never ending ~20% CPU Load
- If one stays with the default (-1), there is no issue at all
- I tried with 1024, 6144, 8192 and also with 2 and 4 (to be sure it is not treated as GB) - none of these works

Does this help to reproduce the issue?

**Comment by egraether** [comment]
Maybe... We will try to reproduce on Windows10. Thanks for the info!

**Comment by mlangkabel** [comment]
We managed to reproduce the issue for Windows 10 with different Java versions, but have not found a fix. 

As a workaround with Sourcetrail 2019.3.23 the JVM Maximum Memory option will be hidden from the preferences when running on Windows 10 and a default value of -1 will be used. 

However, it will still be possible to edit the preferences file manually and provide a custom value if desired which will very likely result in the behavior described here.
