### ISSUE TITLE
macOS crashes when mounting 2019.2.39 .dmg file

### ISSUE THREAD

**Issue by aqiank** [CoatiSoftware/SourcetrailBugTracker#701]
Hi, I downloaded 2019.2.39 .dmg file for macOS 64-bit and tried to mount it on my macOS Mojave 10.14.5 but it froze my macOS for a few seconds before crashing the system. I use APFS (case-insensitive, encrypted) file system.

**Comment by egraether** [comment]
Just tested on macOS Mojave 10.14.4, works fine. Can you please download the package once again and test if it works: https://www.sourcetrail.com/downloads/2019.2.39/osx/64bit
We have had cases were the download corrupted the file.

**Comment by aqiank** [comment]
Hi @egraether 

It still crashes macOS for me. The MD5 checksum is df4462827c9a3600c6e46db640abdbe2. Is that correct?

**Comment by egraether** [comment]
Yes, that's the correct md5 hash.

I updated to macOS Mojave 10.14.5, but still can't reproduce this. The only difference left is that my file system is not encrypted. But I can't test that, due to a Linux partition on the same hard disk.

I uploaded the build as `.zip` here: https://www.sourcetrail.com/downloads#extra

**Comment by aqiank** [comment]
It does work now with the `.zip` version. Thank you very much :D
