### ISSUE TITLE
Show where "using" statements of a namespace are used

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#74]

**Comment by egraether** [comment]
@mlangkabel Was this implemented?

**Comment by mlangkabel** [comment]
Yes, we record the usage of a namespace for cxx using declarations. However, they are only shown in the graph if a definition of that namespace has been indexed and you activate the user node. 

If you activate the namespace, Coati just shows the namespace's contents instead of a node for the namespace itself. And as we have no namespace node, we cannot show the edges pointing to such a node. So this is a UI thing.

**Comment by egraether** [comment]
The places are shown in the code view when activating the namespace
Implemented before 2017.2
